### ISSUE TITLE
Why do we use "public" instead of "external" for our getters?

### ISSUE THREAD

**Issue by IoanSolovastru** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#10]
Hi everyone, great course, congrats Patrick!
I do have a question related to our getters. Why do we use "public" keyword instead of "external". From my knowledge, external is more gas efficient than public.
Code exemple from course:
```solidity
    function getEntrenceFee() public view returns (uint256) {
        return i_entrenceFee;
    }

    function getPlayer(uint256 index) public view returns (address) {
        return s_players[index];
    }

    function getRecentWinner() public view returns (address) {
        return s_recentWinner;
    }

    function getRaffleState() public view returns (RaffleState){
        return s_raffleState;
    }
```

**Comment by velvet-shark** [comment]
If you use external, you won't be able to call these methods from within the contract, only from external sources. We do want to be able to call these methods in the contract itself, too.

**Comment by IoanSolovastru** [comment]
Do we?
Let's take for example **entrenceFee** which has a getter and the variable name i_entrenceFee.
We can easily use i_entrenceFee within our contract, whether it is private or not.

**Comment by PatrickAlphaC** [comment]
You're right, we'd want to make these external! Great eye!

Going to close this issue for now though, since I did `public` in the video I'll keep them as public.
