### ISSUE TITLE
Unit tests stuck forever. Pls help

### ISSUE THREAD

**Issue by olekmorawski** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#102]
Hello ive been battling with a super stupid error for quite some time, so long that I'm slowly loosing my faith in everything.
Something is happening and then i do hh test it gets stuck forever when unit testing on the test "picks a winner, resets the lottery and sends money"

here is a link to my repo if someone wants to have look: https://github.com/olekmorawski/hardhat-smartcontract-lottery-fcc.git

It looks like this: 

```

it("picks a winner, resets the lottery and sends money", async function () {
                  const additionalEntrants = 3
                  const startingAccountIndex = 1
                  const accounts = await ethers.getSigners()
                  for (
                      let i = startingAccountIndex;
                      i < startingAccountIndex + additionalEntrants;
                      i++
                  ) {
                      const accountConnectedRaffle = raffle.connect(accounts[i])
                      await accountConnectedRaffle.enterRaffle({ value: raffleEntranceFee })
                  }
                  const startingTimestamp = await raffle.getLatestTimestamp()

                  await new Promise(async (resolve, reject) => {
                      raffle.once("WinnerPicked", async () => {
                          console.log("Found the event!")
                          try {
                              const recentWinner = await raffle.getRecentWinner()
                              const raffleState = await raffle.getRaffleState()
                              const endingTimestamp = await raffle.getLastTimestamp()
                              const numPlayer = await raffle.getNumberOfPlayers()
                              const winnerEndingBalance = await accounts[1].getBalance()
                              assert.equal(numPlayer.toString(), "0")
                              assert.equal(raffleState.toString(), "0")
                              assert(endingTimestamp > startingTimestamp)

                              assert.equal(
                                  winnerEndingBalance.toString(),
                                  winnerStartingBalance.add(
                                      raffleEntranceFee
                                          .mul(additionalEntrants)
                                          .add(raffleEntranceFee)
                                          .toString()
                                  )
                              )
                          } catch (e) {
                              reject(e)
                          }
                          resolve()
                      })

                      const tx = await raffle.performUpkeep([])
                      const txReciept = await tx.wait(1)
                      const winnerStartingBalance = await accounts[1].getBalance()
                      await vrfCoordinatorV2Mock.fulfillRandomWords(
                          txReciept.events[1].args.requestId,
                          raffle.address
                      )
                  })
              })
          })
      })
```

I dont know how to fix it and setting a time out does not work either.  Lags my whole pc
Pls help

**Comment by RyanPaulGannon** [comment]
I've found a few things and I'll create a Pull Request if you'd like? Your event `WinnerPicked` on your `Raffle.sol` was missing a capital 'W'! 

Your import of `../../helper-hardhat-config` was also changed as it was referencing a directory too far.

**Comment by RyanPaulGannon** [comment]
Also, don't get too disheartened. I was also stuck with troubleshooting this test on my own repo for a pretty long time!

**Comment by olekmorawski** [comment]
@RyanPaulGannon  I changed my testnet to goerli cause i noticed that rinkeby and kovan are now expired, but it did not help, unit tests still gets stuck and even i published it on a testnet i cant even pass the first test :( i have fixed the helper-hardhat-config issue... ill fix the winnerpicked issue now and maybe it will help, i dont understand why my unit tests work localy but when i test them on a testnet they dont

**Comment by olekmorawski** [comment]
@RyanPaulGannon  Okay! Fixed the WinnerPicked and it pushed me a bit forward, now the last test isnt freezing and says :      AssertionError: expected '10000029926991467915050' to equal BigNumber{ …(2) } !!! Im supper happy that it shows me something instead of well...nothing lol.

**Comment by olekmorawski** [comment]
found some more mistakes and fixed them but i dont know what is the source of this one

```
  13 passing (6s)
  1 failing

  1) Lottery Unit Tests
       fulffillRandomWords
         picks a winner, resets the lottery and sends money:

      AssertionError: expected '10000029926991467915050' to equal '10000040000000000000000'    
      + expected - actual

      -10000029926991467915050
      +10000040000000000000000

      at FragmentRunningEvent.<anonymous> (test\unit\Raffle.test.js:154:38)
```

**Comment by RyanPaulGannon** [comment]
I can only read your code on my phone at the moment, but I think you're using two different accounts towards the bottom of your code? 

Try changing them so they're both the same either `[0]`, `[1]` or `[2]`?

**Comment by olekmorawski** [comment]
@RyanPaulGannon  I fixed it, i had a bunch of small errors in my code + you were right with the wrong account numbers - i dont know why tehy are set up this way on the main project GitHub, just misleading

**Comment by olekmorawski** [comment]
:( It still does not work for me when i push it to the testenet 

```
  Lottery Unit Tests
    fulfillRandomWords
Entering Raffle...
Ok, time to wait...
WinnerPicked event fired!
AssertionError: expected '261814855056097286' to equal '251814855056097286'
    at FragmentRunningEvent.<anonymous> (C:\Solidity Course\Hardhat\hardhat-smartcontract-lottery-fcc\test\staging\Raffle.staging.test.js:33:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  showDiff: true,
  actual: '261814855056097286',
  expected: '251814855056097286',
  operator: 'strictEqual'
}
      1) works with live Chainlink Keepers and VRF, we get a randomw winner


  0 passing (2m)
  1 failing
```

**Comment by olekmorawski** [comment]
I dont get how the contract is passing the unit tests but does not pass the one on the testnet. How is this possible, its literally the same test

**Comment by olekmorawski** [comment]
Lol i have ran the test for the second time and it passed - I have no idea how is this possible but ok

**Comment by RyanPaulGannon** [comment]
I believe it's to do with the speed of the test net, if you set your `const txReciept = await tx.wait(1)` to a larger number it may be more consistent.

Are you cool to close this issue now? It may be worth creating a discussion on the course repo if you're still struggling mate.
