### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by coinmasterlisting** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#11]
Hi,

I am getting a error when I try to deploy, followed the code to the word and have searched and have not able to seem to solve it, rather than copying the repository I'd like to see if I can find solutions on my own.

`Error: ERROR processing ***/hardhat-smartcontract-lottery/deploy/00-deploy-mocks.js:
TypeError: Cannot read properties of undefined (reading 'length')
`

Original code from my deploy-mocks.js error states is at line 14, line 14 is at "await":

> const { developmentChains } = require("../helper-hardhat-config")
> 
> const BASE_FEE = ethers.utils.parseEther("0.25") // 0.25 premier, 0.25 link per request
> const GAS_PRICE_LINK = 1e9 //calc value, link per gas
> 
> module.exports = async function ({ getNamedAccounts, deployments }) {
>     const { deploy, log } = deployments
>     const { deployer } = await getNamedAccounts()
>     const args = [BASE_FEE, GAS_PRICE_LINK]
> 
>     if (developmentChains.includes(network.name)) {
>         log("Local network detected, Deploying Mocks")
>         //deploy mock vrfcoordinator
>         await deploy("VRFCoordinatorV2Mock", {
>             from: deployer,
>             logs: true,
>             args: args,
>         })
>         log("Mocks deployed!")
>         log("--------------------------------")
>     }
> }

module.exports.tags = ["all", "mocks"]

Any help would be greatly appreciated thanks.

**Comment by IoanSolovastru** [comment]
Hi, did you import "network"?
```javascript
const {network} = require("hardhat")
```
And just to be sure, check if "developmentChains" has the same name in helper-hardhat-config.js and if so, make sure that you exported it: 
```javascript
module.exports = { developmentChains };
```

**Comment by PatrickAlphaC** [comment]
Could you make these questions on the main discussion repo? Thanks!

And this is the same issue as what we solved here: https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/69
