### ISSUE TITLE
why is the compiler asking to add "abstract" before the contract name ?

### ISSUE THREAD

**Issue by Jaseempk** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#121]
![Screenshot 2022-11-12 075643](https://user-images.githubusercontent.com/99121494/201452477-bf88280b-94fc-4c02-b54a-6104d83b4de3.png)
 
 @krakxn  why is it asking to add the "abstract" term before the contract name?

**Comment by krakxn** [comment]
Good read: https://www.geeksforgeeks.org/solidity-abstract-contract/

Essentially, "Abstract contracts are contracts that have at least one function without its implementation or in the case when you don’t provide arguments for all of the base contract constructors".

**Comment by Jaseempk** [comment]
thanks
