### ISSUE TITLE
Getting error message while deploying to a testnet

### ISSUE THREAD

**Issue by Infatoshi** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#122]
I have tried everything and tried reinstalling a bunch of dependencies but nothing seems to work. As of right now, I don't know what the cause of the problem is. Here is the error message so if anyone else gets the same thing and manages to figure something out then that would help lots. 
`reusing "Raffle" at 0x413375320326d277F674Cf7D220EBc2E8472b587
Verifying...
Verifying contract...
Nothing to compile
[Error: ENOENT: no such file or directory, open 'A:\Desktop\Blockchain & Web3\hh-lottery\artifacts\build-info\f82058629f18742994a2195946c77bc0.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'A:\\Desktop\\Blockchain & Web3\\hh-lottery\\artifacts\\build-info\\f82058629f18742994a2195946c77bc0.json'
}`

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by Infatoshi** [comment]
Apologies Patrick, I posted this to the part 9 issues because it was when
we implemented mocha. I had a timeout error with mocha so I thought it
would be relevant to part 9 issues. Should I save those type of questions
for general issues?

Thanks,
Elliot

**Comment by PatrickAlphaC** [comment]
So, it's just best for the course to put our general questions in the full repo!
