### ISSUE TITLE
Facing error on @chainlink/contracts

### ISSUE THREAD

**Issue by UmerZu** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#124]
Hi !
I install package using yarn add --dev @chainlink/contracts 
and inside of Raffle.sol, I am having error on this import line
import "@chainlink/contracts/src/v0.8/VRFConsumerBaseV2.sol";

**Comment by CarlosHernandez3** [comment]
what solidity extension are you using. The juan blanco one has some dependency issues try switching to hardhat's solidity extension.

**Comment by babelpainterwell** [comment]
Did you solve the issue? I am having the same problem, even with hardhat's solidity extension.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
