### ISSUE TITLE
Peer dependency issue with Hardhat and Chainlink/Contracts 

### ISSUE THREAD

**Issue by CarlosHernandez3** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#129]
There seems to be a peer dependency issue between Hardhat-toolbox and @chainlink/contracts. My exact steps were

1. npm init -y
2. npm install --sav-dev hardhat
3. npx hardhat 
4. select create javascript project
5. npm install @chainlink/contracts 

If I run hardhat compile i get the following error

<img width="620" alt="Screen Shot 2023-01-04 at 11 54 51 AM" src="https://user-images.githubusercontent.com/77164712/210608023-f49bb135-e6f0-46ed-b93b-07837baf8a6d.png">

My hardhat.config has both 

<img width="465" alt="Screen Shot 2023-01-04 at 12 02 03 PM" src="https://user-images.githubusercontent.com/77164712/210609807-ab32b44b-703e-43b9-9c42-86d5867e0f40.png">

My package.json devDependencies are as follows

<img width="790" alt="Screen Shot 2023-01-04 at 1 29 20 PM" src="https://user-images.githubusercontent.com/77164712/210624678-04580a63-4038-4b83-b44d-573b17ae485c.png">

This is my folder structure

<img width="231" alt="Screen Shot 2023-01-04 at 1 43 05 PM" src="https://user-images.githubusercontent.com/77164712/210627135-26b05ad3-279d-48a3-8629-8c8d214d0fbc.png">

My Raffle.sol has zero errors and neither does any the other files in the directory

If you need any other context or information please let me know I really want to progress through the course.  I have tried searching for solutions on youtube and google to no avail.

**Comment by rabobahago** [comment]
Please go to hardhat-smartcontract-lottery-fcc patrick started boilerplate Dependencies in package.json, copy all package.json Dependencies paste them into your project package.json, delete your package.json.lock file and also delete node_modules folder, then run npm install again. It will fix any Dependencies problem.

**Comment by PatrickAlphaC** [comment]
Thanks @rabobahago !

Also,

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
