### ISSUE TITLE
invalid BigNumber value

### ISSUE THREAD

**Issue by bugradursun** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#131]
Is anyone getting bignumber value?My constructor and deployment script's parameters are in the same order.

**Comment by Im-Soumya** [comment]
Yes I am also getting the same error.
```
Error: incorrect data length (argument="gasLane", value={"type":"BigNumber","hex":"0x2386f26fc10000"}, code=INVALID_ARGUMENT, version=abi/5.7.0)
```

**Comment by Im-Soumya** [comment]
This error got fixed after matching the order of the constructor arguments in the contract and deploy script while deploying the contract.
