### ISSUE TITLE
Can't Contribute (Permission Denied)

### ISSUE THREAD

**Issue by teerth17** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#137]
Hii,
Just wanted to do some changes to the 02-deploy program but permission was denied from your account. Creating in changed in my own branch but can't do.

Just want to know if Can Contribute or not

**Comment by PatrickAlphaC** [comment]
Sure! Hit "fork" and create your fork of this repo.

Then, push your changes to your own forked repo, and create a pull request from your repo to this one.
