### ISSUE TITLE
TypeError: vrfCoordinatorV2Mock.createSubscription is not a function

### ISSUE THREAD

**Issue by sravantp03** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#139]
getting `TypeError: vrfCoordinatorV2Mock.createSubscription is not a function` error when trying to deploy.

```
        const transactionResponse = await vrfCoordinatorV2Mock.createSubscription()
        const transactionReceipt = await transactionResponse.wait(1)
        subscriptionId = transactionReceipt.events[0].args.subId
```

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
