### ISSUE TITLE
cannot run performUpkeep() manually. 

### ISSUE THREAD

**Issue by solvman** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#144]
I'd like to see if I can get some help. I'm trying to troubleshoot why my Chainlink Upkeep is not triggering. I checked manually, and checkUpkeep() returns true. However, when I try to run performUpkeep() manually, I get this error: 

**"We were not able to estimate gas. There might be an error in the contract, and this transaction may fail."**

I use the code of the contract from this repository. I verified all of the initialized values are correct. I added the contract to Chainlink VRF and Keepers. Both have been funded with LINK. This is the address of the contract on the Goerli testnet: [0xaA07df8dd1D98b7f657fba1fdDF7f15251926D8f](https://goerli.etherscan.io/address/0xaA07df8dd1D98b7f657fba1fdDF7f15251926D8f)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
