### ISSUE TITLE
Error: Expected 2 Constructor Arguments, got 0

### ISSUE THREAD

**Issue by egutierrez130** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#156]
Hello, I am currently getting an error when trying to deploy during lesson 9. I am on hour 15:19:50. 

This is the current error that I am getting 

Nothing to compile
Local network detected! Deploying mocks...
An unexpected error occurred:

Error: ERROR processing /Users/edgargutierrez/hh-fcc/hardhat-smartcontract-lottery-fcc/deploy/00-deploy-mocks.js:
Error: expected 2 constructor arguments, got 0

I have tried troubleshooting for a few hours now but have yet to find a solution. If possible, some help would be greatly appreciated.  I will attach a link to my github repo, if that is the best way to view the code. 

[Edgars Smart Contract Lottery Repo](https://github.com/egutierrez130/smartcontract-lottery.git)

Thank you!

Also, I have already downgraded my ethers to version 5.7.2

**Comment by egutierrez130** [comment]
UPDATE: I fixed the above, but now it is throwing a different error:

Error: ERROR processing /Users/edgargutierrez/hh-fcc/hardhat-smartcontract-lottery-fcc/deploy/01-deploy-raffle.js:
ReferenceError: vrfCoordinatorV2Mock is not defined
    at Object.module.exports [as func] (/Users/edgargutierrez/hh-fcc/hardhat-smartcontract-lottery-fcc/deploy/01-deploy-raffle.js:15:9)

**Comment by egutierrez130** [comment]
UPDATE! 
No more Errors! (so happy! hours and hours of debugging and googling)

Things that are now functioning:
1. Contracts are now deploying.
2. Raffle Unit Tests are now passing and working. (no more errors thrown)

My solution was to replace _(["all"])_ for  _(["mocks", "raffle"])_  in the Raffle.test.js file

My guess is that it wasn't able to read/connect to all the other files with _all_ but it would be nice to get some clarification from someone more seasoned. 


`beforeEach(async () => {
              const { deployer } = await getNamedAccounts()
              await deployments.fixture(["mocks", "raffle"])
              raffle = await ethers.getContract("Raffle", deployer)
              vrfCoordinatorV2Mock = await ethers.getContract("VRFCoordinatorV2Mock", deployer)
          })`

Hope this helps someone in distress as well. Cheers to moving on!

**Comment by PatrickAlphaC** [comment]
Awesome work!! 

But, can you ask here:
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by egutierrez130** [comment]
> Awesome work!!
> 
> But, can you ask here: Can you:
> 
> 1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
> 2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

Thanks @PatrickAlphaC 
I will definitely add the question into the full repo.  Thanks for linking the video for formatting questions.
