### ISSUE TITLE
Error: No Contract deployed with name VRFCoordinatorV2Mock in unit testing

### ISSUE THREAD

**Issue by abdullahtanvir11** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#157]
![Capture1](https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/assets/109508166/447feb50-fae1-4812-97d7-35fe594ba8b0)
this error occurs by running yarn hardhat test
This error doesnot occur on running yarn hardhat deploy

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
