### ISSUE TITLE
Question - what calls the fulfillRandomWords function in our contract?

### ISSUE THREAD

**Issue by Ahmedborwin** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#159]
Hi,

Embarrassed to be asking this question, but, I can't figure out how our fulfillRandomWords function is called once our performupkeep function is successfully completed. IS is something to do with our vrfcoordinator.requestRandomWords function call?

Any help is much appreciated :)

**Comment by PatrickAlphaC** [comment]
Questions are how we learn! No need to be embarrassed. 

Could you do me a favor though.

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
