### ISSUE TITLE
Error: cannot estimate gas; transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by zeeshan615** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#161]
running "hh run scripts/mockOffchain.js --network sepolia" 
PatrickAlphaC lesson 9
repo link: https://github.com/zeeshan615/nextjs-smartContract-Lottery

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
