### ISSUE TITLE
Missing revert data (action="estimateGas", data=null, reason=null

### ISSUE THREAD

**Issue by AhsanAnwar1996** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#164]
I'm facing this error while deploying first contract locally through ganache & Metamask, can you please help me

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
