### ISSUE TITLE
Event listener not working in staging test.

### ISSUE THREAD

**Issue by rajdama** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#166]
My chainlink keeper is working properly and performupkeep is getting triggered but raffle.once() is not able to catch the winnerpicked event. What should i do?

**Comment by rajdama** [comment]
@PatrickAlphaC I think their is some dependencies issue due to which many folks are facing problem in staging test section. Please look into it what set of dependence are creating the problem.

**Comment by PatrickAlphaC** [comment]
Hmm... yes likely some of the packages were updated. Could you try git cloning this repo and see if you still get the error?

**Comment by rajdama** [comment]
@PatrickAlphaC  I copied package.json file from this repo and now its seems to be working fine. But I am not able to call fullfillrandomwords function everything else working fine. I contacted one of the chainlink support guy, he told me that u must have real funds in metamask even if you are testing chainlinkvrf on sepolia testnet. Can u plz suggest me what should I do?

**Comment by PatrickAlphaC** [comment]
You don't need real funds on metamask... If you're really struggling with Sepolia here, my advice would be you can just proceed with the course. Getting the testnet parts to work 100% aren't necessary.
