### ISSUE TITLE
 Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves

### ISSUE THREAD

**Issue by asalrahman** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#170]
getting this error while unit test 
1) Lottery
       enterLottery
         performUpkeep
           picks a winner,rest lottery and send money to winner:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\ACER\ether.js\Lottery\test\Lottery.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
