### ISSUE TITLE
Unable to import "@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol" in test/VRFCoordinatorV2Mock.sol 

### ISSUE THREAD

**Issue by AbhimanyuAjudiya** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#207]
The VRFCoordinatorV2Mock.sol does not exist in mocks dir...

**Comment by AbhimanyuAjudiya** [comment]
I should be changed to this: 
import "@chainlink/contracts/src/v0.8/vrf/mocks/VRFCoordinatorV2Mock.sol";

**Comment by PatrickAlphaC** [comment]
I'm going to be deprecating this repo soon, thanks for flagging this!
