### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by codebaya** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#24]
I'v tried to solve this issue but I couldn't 
What I tried to do is to fix "const { deployer } = getNamedAccounts();" this one,
Becuase when I test as console.log(deployer), it came out "undefined"
Maybe that's why TypeError: Cannot read properties of undefined (reading 'length')
If anybody know how to fix this issue, Please let me know

Thanks

 │  ~/Doc/hardhat-sc-lottery  hh deploy                                                1 ✘ │ 23:13:47  
Nothing to compile
Local network detected! Deploying mocks...
deploying "VRFCoordinatorV2Mock" (tx: 0x1319418ccc7f88788f4cc6c636585b9e49e87dafc1fca4cccb96f87be089ac55)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 1803306 gas
Mocks Deployed!
----------------------------------------------------------
You are deploying to a local network, you'll need a local network running to interact
Please run `yarn hardhat console --network localhost` to interact with the deployed smart contracts!

An unexpected error occurred:

Error: ERROR processing /Users/glory/Documents/hardhat-sc-lottery/deploy/01-deploy-raffle.js:
TypeError: Cannot read properties of undefined (reading 'length')
    at getFrom (/Users/glory/Documents/hardhat-sc-lottery/node_modules/hardhat-deploy/src/helpers.ts:1713:14)
    at _deploy (/Users/glory/Documents/hardhat-sc-lottery/node_modules/hardhat-deploy/src/helpers.ts:533:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at _deployOne (/Users/glory/Documents/hardhat-sc-lottery/node_modules/hardhat-deploy/src/helpers.ts:1004:16)
    at Object.module.exports [as func] (/Users/glory/Documents/hardhat-sc-lottery/deploy/01-deploy-raffle.js:46:20)
    at DeploymentsManager.executeDeployScripts (/Users/glory/Documents/hardhat-sc-lottery/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)

```
------- 01-deploy-raffle.js -----------

const { network, getNamedAccounts, deployments, run, ethers } = require("hardhat")
const { developmentChains, networkConfig,
    VERIFICATION_BLOCK_CONFIRMATIONS }
    = require("../helper-hardhat-config")
const { verify } = require("../utils/verify")

const FUND_AMOUNT = ethers.utils.parseEther("2")

module.exports = async function({getNamedAccounts, deployments}) {
    const { deploy, log } = deployments
    const { deployer } = getNamedAccounts();
    console.log("deployer :1", deployer)        <<<<<<<<<<<<<<<<<<<<----- it turned out "undefined"
    console.log("deploy : 2", deploy)
    const chainId = network.config.chainId
    let vrfCoordinatorV2Address, subscriptionId

    if (chainId == 31337) {
        // create VRFV2 Subscription
        const vrfCoordinatorV2Mock = await ethers.getContract("VRFCoordinatorV2Mock")
        vrfCoordinatorV2Address = vrfCoordinatorV2Mock.address
        const transactionResponse = await vrfCoordinatorV2Mock.createSubscription()
        const transactionReceipt = await transactionResponse.wait()
        subscriptionId = transactionReceipt.events[0].args.subId
        // Fund the subscription
        // Usually, you'd need the link token on a real network
        // await vrfCoordinatorV2Mock.fundSubscription(subscriptionId, FUND_AMOUNT)
    } else {
        vrfCoordinatorV2Address = networkConfig[chainId]["vrfCoordinatorV2"]
        subscriptionId = networkConfig[chainId]["subscriptionId"]
    }

    const waitBlockConfirmations = (chainId == 31337)
        ? 1
        : VERIFICATION_BLOCK_CONFIRMATIONS

    log("----------------------------------------------------")

    const entranceFee = networkConfig[chainId]["entranceFee"]
    const gasLane = networkConfig[chainId]["gasLane"]
    const callbackGasLimit = networkConfig[chainId]["callbackGasLimit"]
    const interval = networkConfig[chainId]["interval"]
    const args = [vrfCoordinatorV2Address,
        entranceFee, gasLane, subscriptionId,
        callbackGasLimit, interval]

    const raffle = await deploy("Raffle", {
        from: deployer,
        args: args,
        log: true,
        waitConfirmations: waitBlockConfirmations
    })

    if(!developmentChains.includes(network.name) && process.env.ETHERSCAN_API_KEY) {
        log("Verifying...")
        await verify(raffle.address, args)
    }
    log("-----------------------------------")
}

module.exports.tags = ["all", "raffle"]

**Comment by codebaya** [comment]
oach~ 
I figured out this one 
it's misspell type-error
const { deployer } = getNamedAccounts(); => const { deployer } = await getNamedAccounts();"
But still occurred error like this 
``` Error: value out-of-bounds (argument="callbackGasLimit", value="100000000000000000", code=INVALID_ARGUMENT, version=abi/5.6.4)

So I fixed it as changing the order
```
networkConfig[chainId]["callbackGasLimit"],
networkConfig[chainId]["entranceFee"],

I don't know why it should be like this. but problem's solved
(if anybody know this, Please comment below)

**Comment by TakeAwayAntun** [comment]
Excuse me, is this problem solved?  If you solve it,   please tell me.  thank you every much .

**Comment by krakxn** [comment]
Try my solution.

**Comment by TakeAwayAntun** [comment]
i have solved this problem 
change this arg , add  ( await ) , like this
```solidity
const { deployer } = await getNamedAccounts();
```

**Comment by Dharshan-K** [comment]
Guys I am getting the same error. but from the 00-deploy-mocks.js file.

Error: ERROR processing D:\ethereum\smart_contract_lottery\deploy\00-deploy-mocks.js:
TypeError: Cannot read properties of undefined (reading 'length')

I tried the above solutions. but again I am getting the same error.

My code 00-deploy-mocks.js

```/** @format */

const { getNamedAccounts, deployments, network, ethers } = require("hardhat");

const BASE_FEE = 250000000000000000; // 0.25 is this the premium in LINK?
const GAS_PRICE_LINK = 1e9; // link per gas, is this the gas lane? // 0.000000001 LINK per gas

module.exports = async ({ getNamedAccounts, deployments }) => {
  const { deploy, log } = deployments;
  const { deployer } = await getNamedAccounts();
  const chainId = network.config.chainId;
  // If we are on a local development network, we need to deploy mocks!
  if (chainId == 31337) {
    log("Local network detected! Deploying mocks...");
    await deploy("VRFCoordinatorV2Mock", {
      from: deployer,
      log: true,
      args: [BASE_FEE, GAS_PRICE_LINK],
    })

    log("Mocks Deployed!");
    log("----------------------------------------------------------");
    log(
      "You are deploying to a local network, you'll need a local network running to interact"
    );
    log(
      "Please run `yarn hardhat console --network localhost` to interact with the deployed smart contracts!"
    );
    log("----------------------------------------------------------");
  }
};
module.exports.tags = ["all", "mocks"];

```

If anyone knows how to debug. comment below

**Comment by PatrickAlphaC** [comment]
Nice work :D 

Closing for now. Thanks all for jumping in!
