### ISSUE TITLE
Error: No Contract deployed with name VRFCoordinatorV2Mock

### ISSUE THREAD

**Issue by r0ushann** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#28]
I'm getting this error after 15:19:00
 at command `yarn hardhat compile`

Nothing to compile
An unexpected error occurred:

Error: ERROR processing C:\Users\roush\newHardhatLottery\deploy\01-deploy-raffle.js:
Error: No Contract deployed with name VRFCoordinatorV2Mock
    at Object.getContract (C:\Users\roush\newHardhatLottery\node_modules\

**Comment by PatrickAlphaC** [comment]
Can you ask in the full repo? Thanks!

https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
