### ISSUE TITLE
Can't register upKeep

### ISSUE THREAD

**Issue by RohitSingh107** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#30]
UI of https://keepers.chain.link/new have changed (it's different from UI shown in tutorial of FreeCodeCamp lesson 9) I can't figure out how to properly register upkeep with this new UI, It always got stuck in this unresponsive page 
![image_2022-07-14_00-01-05](https://user-images.githubusercontent.com/64142943/178807150-9b29a513-bf1c-47c7-8880-16e7f7443c4c.png)

Please help

**Comment by effiongcharles** [comment]
Hi,

Please try to register the upkeep as **custom** instead of "**time triggered.**"

Regards,
Charles

**Comment by PatrickAlphaC** [comment]
Thanks Charles!
