### ISSUE TITLE
Estimating gasLane on helper-hardhat-config file for deployment on avalanche mainnet

### ISSUE THREAD

**Issue by abondance68** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#32]
I plan to deploy Raffle.sol on the avalanche mainnet & i have issue estimating the gas lane . On chainlink docs, they have 3 tiers:

- 200 gwei Key Hash
- 500 gwei Key Hash
- 1000 gwei Key Hash

Which one to choose? 
Oddly enough gwei is irrevelant in avalanche, gas is calculated in nAvax as 1 nAVAX is equal to 0.000000001 AVAX

**Comment by PatrickAlphaC** [comment]
Can you ask this on stack exchange ETH? Thank you!

https://ethereum.stackexchange.com/
