### ISSUE TITLE
Prevent Upkeep to be called by anyone

### ISSUE THREAD

**Issue by bricedenice59** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#34]
Hello everyone and if you @PatrickAlphaC are reading me, I would like to thank you for the quality of your teaching, your lessons are valuable to me.

I wanted to ask how to deal with the performUpKeep interaction permissions, since Chainlink needs this contract function to be public, everyone can interact with it and anyone can send a transaction with it.
Let’s say the conditions to call the perfomUpKeep are always met, at least 1 player, etc…
So anyone malicious can just call this function as many times as they want, besides that, a winner will be picked up without any need of a chainlink keepUp, and worst is that this could lead to empty your funds from your consumer in Chainlink vrf as random number(s) will be generated every time performUpKeep is called.
Can we rely on chainlink contract address that is making the call to the function? Can we apply a modifier?

Appreciate your time and your help.
Brice

**Comment by PatrickAlphaC** [comment]
Great question. Basically the answer is you do some validation on performUpkeep as we show in the video, to make sure that the function is only called... when you want it to be called.

Then, if someone "malicious" calls it, that's fine, because it'll just save you some LINK and still only get called when you want it to. 

Please ask future questions on the full repo. Thanks! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-js

**Comment by bricedenice59** [comment]
Hi @PatrickAlphaC

Off topic, I was searching a way to get my lottery contract to be upgradable as I wanted to change a few rules for the lottery to pick up a winner and I have come across the retro-cats-contracts repository and checking for the code answers my question related to prevent malicious calls to the performUpKeeps function :)
[ https://github.com/retro-cats/retro-cats-contracts/blob/8df144eb225371feaa13e687b85d1733c6353b66/contracts/RetroCats.sol]( https://github.com/retro-cats/retro-cats-contracts/blob/8df144eb225371feaa13e687b85d1733c6353b66/contracts/RetroCats.sol)

They have a modifier: onlyChainlinkKeepers() 
They prevent performUpKeep to be called by anybody else than a chainlink node...

Regards
Brice

**Comment by PatrickAlphaC** [comment]
@bricedenice59 ahah - actually, that's really not best practice. You don't want to do that. 

Want you want to do instead is just validate that the performUpkeep can only be called when it needs to be called, no matter who calls it.
