### ISSUE TITLE
Peer dependency issue with Hardhat and Chainlink/Contracts

### ISSUE THREAD

**Issue by mertdeveci5** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#42]
There is a peer dependency issue between Hardhat-ethers version and @chainlink/contracts package. I tried using `--force` but now hardhat is not compatible and getting a ```Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.``` error. How can I resolve this? 

![image](https://user-images.githubusercontent.com/83559696/183266077-64ef0044-ec14-4815-ab8e-cc234733bac2.png)

**Comment by PatrickAlphaC** [comment]
What were the exact steps you took to get this error? The exact commands you ran from start to error?

**Comment by mertdeveci5** [comment]
Basically only cloning hardhat-starter-kit to start a new project and then compiling through `npx hardhat compile` When I run the command, I come across the below again which is the same with above. I cannot also run `npm install @nomiclabs/hardhat-waffle` etc as it returns the same dependency issue. 
![image](https://user-images.githubusercontent.com/83559696/184479293-736b6a6a-fcf9-413e-ac6e-8b66c0980667.png)

**Comment by PatrickAlphaC** [comment]
I need the exact steps, starting from git clone:

```
git clone https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc
cd hardhat-smartcontract-lottery-fcc
yarn
yarn hardhat test
```

Closing for now, feel free to re-open with exact steps taken.
