### ISSUE TITLE
getRaffleState() returning 0 or 1 

### ISSUE THREAD

**Issue by IbrahimSam96** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#47]
gm all. Anyone experienced retrieving s_raffleState value from the front-end using the public view `getRaffleState() `?

Strangely, I'm getting back 0 or 1. Any thoughts?

**Comment by jamsubzero** [comment]
That's as expected. s_raffleState actually stores the index of the RaffleState enum. So that would be 0 for OPEN and 1 for CALCULATING.
