### ISSUE TITLE
getLatestTimeStamp() is not a raffle function. raffle uses getLastTimeStamp

### ISSUE THREAD

**Issue by sagapiou** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#5]
https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/32f198ae019b1da5ba6491eb49fd22a9377036c3/test/staging/Raffle.staging.test.js#L20

https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/32f198ae019b1da5ba6491eb49fd22a9377036c3/test/staging/Raffle.staging.test.js#L34

**Comment by PatrickAlphaC** [comment]
Whoops!

You're right! It should be `getLastTimeStamp`

**Comment by PatrickAlphaC** [comment]
Fixed
