### ISSUE TITLE
Error HH404: File @chainlink/contracts/src/v0.8.interfaces/KeeperCompatibleInterface.sol, imported from contracts/Raffle.sol, not found.

### ISSUE THREAD

**Issue by quasar0x** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#54]
Did anyone else experience this error?

**Comment by joWexler** [comment]
Well I guess you have to run `npm install @chainlink/contrats` inside your working directory, but this issue is not very informative unfortunately.

**Comment by quasar0x** [comment]
Yeap!. I fixed it actually. Did just that and it worked. :)

**Comment by joWexler** [comment]
That's great, don't forget to close the issue!

**Comment by PatrickAlphaC** [comment]
Nice work!
