### ISSUE TITLE
A possible attack on the "Raffle".

### ISSUE THREAD

**Issue by KumaCrypto** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#57]
Contracts cannot accept ETH if they do not have **receive** or **fallback** functions. It follows from this that if a smart contract participates in the lottery and wins an error will occur, on the line:
[(bool success, ) = recentWinner.call{value: address(this).balance}("");](https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/0bec7c9948a06aad4cf7feb44570d1d830264c55/contracts/Raffle.sol#L158) ,
since it simply will not be able to accept ETH. 

To avoid this situation, we can check the presence of a bytecode from a potential participant when he is just trying to enter the lottery, in the following way:
`if (msg.sender.code.length > 0) revert Raffle__OnlyForEOA();`

In theory, after an error occurs, Chainlink Keeper will call **performUpkeep** in the next block, since **checkUpkeep** will still return true. Therefore, it's not too scary, but we will lose our Link tokens, which are spent on VRF v2 and Chainlink Keeper.

PS: I understand that this is an educational course and at such an early stage it would be difficult to explain different types of attacks, but I decided it was worth mentioning)

**Comment by othaime-en** [comment]
Nice catch! @KumaCrypto 
I'm interested in the various attacks on smart contracts would you mind collaborating or maybe sharing resources about these attacks?

**Comment by KumaCrypto** [comment]
Thanks @othaime-en ! I am always happy to collaborate with people motivated for development, so welcome, in the profile you can find how to interact with me.

Regarding this type of attack is denial of service (DoS), you can find a lot of resources on this. A real example of this type of attack is the "King of the Ether" project.

Examples and explanations can also be found at the links: [here](https://medium.com/@Knownsec_Blockchain_Lab/in-depth-understanding-of-denial-of-service-vulnerabilities-dd437b1d7a1c#:~:text=In%20Solidity%2C%20a%20DoS%20vulnerability,original%20contract%20code%20logic%20unworkable.) (point 3.3) and [here](https://consensys.github.io/smart-contract-best-practices/attacks/denial-of-service/). (I hope it is allowed to leave links to third-party resources here for educational purposes). 

The resources that I have indicated above consider a slightly different case in contrast to the lottery, but I hope this will give enough understanding! :)

**Comment by KumaCrypto** [comment]
@PatrickAlphaC I agree, you're right! I don't want to deprive other smart contracts of the opportunity to interact with our lottery! 

Then, instead of directly sending native currency (for example, ETH) inside the **fulfillRandomWords** function, we can create a separate function, for example, "withdraw" for the winners. 
Then there will definitely be no errors during the oracle transaction, and also maybe we will pay less for callbackGasLimit :)
Only in this case it will be necessary to additionally store information about who won how much.

I'm not calling for anything to be corrected, it's just that if anyone reads, they might be inspired by the idea and do it themselves :)

**Comment by othaime-en** [comment]
Thanks @KumaCrypto. I'll definitely keep in touch if I have a project coming up.

**Comment by PatrickAlphaC** [comment]
Yes! Anytime you're using a dynamic array you run into a chance for denial of service attacks!
