### ISSUE TITLE
ERROR processing skip func of Error: value must be a string

### ISSUE THREAD

**Issue by xsaad67** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#58]
I'm trying to deploy the VRFCoordinator but getting this error 
Error: ERROR processing skip func D:\blockchain-dev\hardhat-lottery\deploy\00-deploy-mocks.js:
Error: value must be a string (argument="value", value=0.01, code=INVALID_ARGUMENT, version=units/5.7.0)

My VRFCoordinatorMockV2 deploy is:

`const { developmentChains } = require('../helper-hardhat-config');
const { network, ethers } = require("hardhat");

const BASE_FEE = ethers.utils.parseEther("0.25");
const GAS_PRICE_LINK = 1e9;

module.exports = async function ({ getNamedAccounts, deployments }) {
    const { deploy, log } = deployments;
    const { deployer } = await getNamedAccounts();

    const args = [BASE_FEE, GAS_PRICE_LINK];

    if (developmentChains.includes(network.name)) {
        log("Localhost detected");
        //Deploy mock
        await deploy("VRFCoordinatorV2Mock", {
            from: deployer,
            log: true,
            args: args,

        });
        log("Mock Deployed");
        log("---------------------------------");
    }
}
`

Here I'm parsing the ether and tried GAS_PRICE_LINK with `100000000` but still getting the same error with no luck.

I tried to replicate the same with Remix and got successfully deployed. but in deployment it's getting stuck on the same error.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
