### ISSUE TITLE
const recentWinner spelling. It is used as recentWinner in line 37 so either line 31 or line 37 should change

### ISSUE THREAD

**Issue by sagapiou** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#6]
https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/32f198ae019b1da5ba6491eb49fd22a9377036c3/test/staging/Raffle.staging.test.js#L31

**Comment by PatrickAlphaC** [comment]
Fixed, thank you!
