### ISSUE TITLE
Question: checkUpkeep

### ISSUE THREAD

**Issue by shkarfz** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#7]
If `checkUpkeep` is called everytime and decides on the basis of bool value to call the `performUpkeep` or not. Then in our raffle contract does it even make sense to call the `checkUpkeep` again inside  `performUpkeep` ? will it save gas if we don't call it?
```
function checkUpkeep(bytes calldata /* checkData */) public  override returns(bool upkeepNeeded, bytes memory /* performData */){}

function performUpkeep(bytes calldata /* performData */) external override {
   (bool upkeepNeeded, ) = checkUpkeep("");
}
```

**Comment by PatrickAlphaC** [comment]
Can you ask on the main repo? Thank you! 

https://github.com/smartcontractkit/full-blockchain-solidity-course-js
