### ISSUE TITLE
Compilation error in checkUpKeep function

### ISSUE THREAD

**Issue by trytocatcharg** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#70]
Hello, i'm facing this error and the solution dont compile
![image](https://user-images.githubusercontent.com/18711533/189378752-871b0289-5240-46ba-bac7-96bf465b35c2.png)

This is my hardhat config and the version of my contract is 0.8.7:

            require("@nomiclabs/hardhat-waffle");
            require("@nomiclabs/hardhat-etherscan");
            require("hardhat-deploy");
            require("solidity-coverage");
            require("hardhat-gas-reporter");
            require("hardhat-contract-sizer");
            require("dotenv").config();
            
            /** @type import('hardhat/config').HardhatUserConfig */
            module.exports = {
              solidity: "0.8.7",
            };

am i doing something wrong?
Thank you!

**Comment by trytocatcharg** [comment]
ok.... Patricks fixes it during the video :)
sorry

**Comment by labib147** [comment]
That needs to be "memory" I believe. String is  of type Memory not calldata as far as I recall.

**Comment by abdullahtanvir11** [comment]
> ok.... Patricks fixes it during the video :) sorry

where did he fix this?
