### ISSUE TITLE
Wrong chain ID in the code repo associated with lesson 9

### ISSUE THREAD

**Issue by 0xYoyo** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#81]
After goreli update you forgot to swap out the previous rinkeby chainID from 4 to 5 in helper-hardhat-config.js 👍 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/113042560/191516140-8525f82a-0318-4f7a-a030-a0ab7f0890c9.png">

**Comment by kihiuFrank** [comment]
Noted that too.

**Comment by PatrickAlphaC** [comment]
Fixed!
