### ISSUE TITLE
Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

### ISSUE THREAD

**Issue by mubashirhussainkhadim** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#9]
i am facing this error i try  many times , compare with other repositories but i am stuck on this error 
its show perfom keepup but show pending on Vrf Subscription 
i want to continue but stuck on this 
my subscription id : 6212
keeper address : 0x5796CeAD9f7027bb771b698449e479Ee62439955
my contract address : https://rinkeby.etherscan.io/address/0x5796CeAD9f7027bb771b698449e479Ee62439955
my repo : https://github.com/mubashirhussainkhadim/hardhat-lottery
`  Raffle Unit Tests
    fulfillRandomWords
Setting up test...
Setting up Listener...
Entering Raffle...
Ok, time to wait...
      1) works with live Chainlink Keepers and Chainlink VRF, we get a random winner

  0 passing (5m)
  1 failing

  1) Raffle Unit Tests
       fulfillRandomWords
         works with live Chainlink Keepers and Chainlink VRF, we get a random winner:
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mubashirkhadim/Downloads/hardhat-smartcontract-lottery-main/test/staging/Raffle.staging.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)`
<img width="1440" alt="Screenshot 2022-06-10 at 5 12 55 AM" src="https://user-images.githubusercontent.com/66620586/172965598-be74a787-3129-4292-8f3c-df807e6c5d67.png">
<img width="1440" alt="Screenshot 2022-06-10 at 5 13 37 AM" src="https://user-images.githubusercontent.com/66620586/172965602-bafe28d4-4298-4db6-b60e-49596af579c7.png">
<img width="1440" alt="Screenshot 2022-06-10 at 5 16 34 AM" src="https://user-images.githubusercontent.com/66620586/172965777-49de4b26-0c9d-4f41-888d-e23351519415.png">

**Comment by 0xMudded** [comment]
I think Rinkeby might be facing some issues lately. Adding extra link to my subscription seemed to fixed this error for me.

**Comment by mubashirhussainkhadim** [comment]
i try many times almost 50 times same issue

**Comment by ke1caM** [comment]
I had the same issue. I funded VRF subscription with extra 3 LINK tokens ( total amount 5 LINK tokens ) and it worked.

**Comment by mubashirhussainkhadim** [comment]
Okay i will try this

**Comment by mubashirhussainkhadim** [comment]
[ke1caM](https://github.com/ke1caM) brother thanks 


  Raffle Unit Tests
    fulfillRandomWords
Setting up test...
Setting up Listener...
Entering Raffle...
Ok, time to wait...
WinnerPicked event fired!
      ✔ works with live Chainlink Keepers and Chainlink VRF, we get a random winner (105619ms)


  1 passing (2m)
issue is resolved by adding more link to vrf subscription
