### ISSUE TITLE
  Error: VM Exception while processing transaction

### ISSUE THREAD

**Issue by eth-dev00** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#96]
hey guys 
i try to write the test for the raffle but  at the  "does not allow entrance when raffle is calculating" in the EnterRaffle descrie 
get the following error :
> Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'
 at VRFCoordinatorV2Mock.onlyValidConsumer (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:72)
    at VRFCoordinatorV2Mock.requestRandomWords (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:147)
    at Raffle.performUpkeep (contracts/Raffle.sol:142)

when i run the perforUpkeep() method i get this error i don't know how to fix it because i don't understand why InvalidConsumer() get reverted . i would appreciate it if anyone can help ?

**Comment by RyanPaulGannon** [comment]
Have a look at this https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/issues/46#issuecomment-1215100931 

Let us know if it works, I've had this error myself in the past too ...

**Comment by RyanPaulGannon** [comment]
All sorted now?

**Comment by 0xKMG** [comment]
just found out there's a solution out there for it after submitting (my first) pull request, I guess installing an older version of chainlink contracts works as well?

**Comment by RyanPaulGannon** [comment]
Hey, can we close this now?

**Comment by PatrickAlphaC** [comment]
Closing, thanks!
